PackageIdentifier: scmccart.mked
PackageVersion: 0.0.0
Platform:
  - Windows.Desktop
MinimumOSVersion: 10.0.0.0
InstallerType: portable
Installers:
  - Architecture: x64
    InstallerUrl: <RELEASE_URL>/mked-win-x64.exe
    InstallerSha256: <SHA256>
    InstallerType: portable
ManifestType: installer
ManifestVersion: 1.6.0
